<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pays')->delete();
		$pays = array (
			array ( 'id' => 1 , 'code' => 'AF' , 'name' => " Afghanistan ", 'phonecode' => 93 ),
			array ( 'id' => 2 , 'code' => 'AL' , 'name' => " Albanie ", 'phonecode' => 355 ),
			array ( 'id' => 3 , 'code' => 'DZ' , 'name' => " Algérie ", 'phonecode' => 213 ),
			array ( 'id' => 4 , 'code' => 'AS' , 'name' => " Samoa américaines ", 'phonecode' => 1684 ),
			array ( 'id' => 5 , 'code' => 'AD' , 'name' => " Andorre ", 'phonecode' => 376 ),
			array ( 'id' => 6 , 'code' => 'AO' , 'name' => " Angola ", 'phonecode' => 244 ),
			array ( 'id' => 7 , 'code' => 'AI' , 'name' => " Anguilla ", 'phonecode' => 1264 ),
			array ( 'id' => 8 , 'code' => 'AQ' , 'name' => " Antarctique ", 'phonecode' => 0 ),
			array ( 'id' => 9 , 'code' => 'AG' , 'name' => " Antigua-et-Barbuda ", 'phonecode' => 1268 ),
			array ( 'id' => 10 , 'code' => 'AR' , 'name' => " Argentine ", 'phonecode' => 54 ),
			array ( 'id' => 11 , 'code' => 'AM' , 'name' => " Arménie ", 'phonecode' => 374 ),
			array ( 'id' => 12 , 'code' => 'AW' , 'name' => " Aruba ", 'phonecode' => 297 ),
			array ( 'id' => 13 , 'code' => 'AU' , 'name' => " Australie ", 'phonecode' => 61 ),
			array ( 'id' => 14 , 'code' => 'AT' , 'name' => " Austria ", 'phonecode' => 43 ),
			array ( 'id' => 15 , 'code' => 'AZ' , 'name' => " Azerbaïdjan ", 'phonecode' => 994 ),
			array ( 'id' => 16 , 'code' => 'BS' , 'name' => " Bahamas The ", 'phonecode' => 1242 ),
			array ( 'id' => 17 , 'code' => 'BH' , 'name' => " Bahreïn ", 'phonecode' => 973 ),
			array ( 'id' => 18 , 'code' => 'BD' , 'name' => " Bangladesh ", 'phonecode' => 880 ),
			array ( 'id' => 19 , 'code' => 'BB' , 'name' => " Barbade ", 'phonecode' => 1246 ),
			array ( 'id' => 20 , 'code' => 'BY' , 'name' => " Biélorussie ", 'phonecode' => 375 ),
			array ( 'id' => 21 , 'code' => 'BE' , 'name' => " Belgium ", 'phonecode' => 32 ),
			array ( 'id' => 22 , 'code' => 'BZ' , 'name' => " Bélize ", 'phonecode' => 501 ),
			array ( 'id' => 23 , 'code' => 'BJ' , 'name' => " Bénin ", 'phonecode' => 229 ),
			array ( 'id' => 24 , 'code' => 'BM' , 'name' => " Bermudes ", 'phonecode' => 1441 ),
			array ( 'id' => 25 , 'code' => 'BT' , 'name' => " Bhoutan ", 'phonecode' => 975 ),
			array ( 'id' => 26 , 'code' => 'BO' , 'name' => " Bolivie ", 'phonecode' => 591 ),
			array ( 'id' => 27 , 'code' => 'BA' , 'name' => " Bosnie-Herzégovine ", 'phonecode' => 387 ),
			array ( 'id' => 28 , 'code' => 'BW' , 'name' => " Botswana ", 'phonecode' => 267 ),
			array ( 'id' => 29 , 'code' => 'BV' , 'name' => " Ile Bouvet ", 'phonecode' => 0 ),
			array ( 'id' => 30 , 'code' => 'BR' , 'name' => " Brazil ", 'phonecode' => 55 ),
			array ( 'id' => 31 , 'code' => 'IO' , 'name' => " Territoire britannique de l'océan Indien ", 'phonecode' => 246 ),
			array ( 'id' => 32 , 'code' => 'BN' , 'name' => " Brunei ", 'phonecode' => 673 ),
			array ( 'id' => 33 , 'code' => 'BG' , 'name' => " Bulgarie ", 'phonecode' => 359 ),
			array ( 'id' => 34 , 'code' => 'BF' , 'name' => " Burkina Faso ", 'phonecode' => 226 ),
			array ( 'id' => 35 , 'code' => 'BI' , 'name' => " Burundi ", 'phonecode' => 257 ),
			array ( 'id' => 36 , 'code' => 'KH' , 'name' => " Cambodge ", 'phonecode' => 855 ),
			array ( 'id' => 37 , 'code' => 'CM' , 'name' => " Cameroun ", 'phonecode' => 237 ),
			array ( 'id' => 38 , 'code' => 'CA' , 'name' => " Canada ", 'phonecode' => 1 ),
			array ( 'id' => 39 , 'code' => 'CV' , 'name' => " Cap Vert ", 'phonecode' => 238 ),
			array ( 'id' => 40 , 'code' => 'KY' , 'name' => " Îles Caïmans ", 'phonecode' => 1345 ),
			array ( 'id' => 41 , 'code' => 'CF' , 'name' => " République centrafricaine ", 'phonecode' => 236 ),
			array ( 'id' => 42 , 'code' => 'TD' , 'name' => " Tchad ", 'phonecode' => 235 ),
			array ( 'id' => 43 , 'code' => 'CL' , 'name' => " Chili ", 'phonecode' => 56 ),
			array ( 'id' => 44 , 'code' => 'CN' , 'name' => " Chine ", 'phonecode' => 86 ),
			array ( 'id' => 45 , 'code' => 'CX' , 'name' => " Christmas Island ", 'phonecode' => 61 ),
			array ( 'id' => 46 , 'code' => 'CC' , 'name' => " Îles Cocos (Keeling) ", 'phonecode' => 672 ),
			array ( 'id' => 47 , 'code' => 'CO' , 'name' => " Colombie ", 'phonecode' => 57 ),
			array ( 'id' => 48 , 'code' => 'KM' , 'name' => " Comores ", 'phonecode' => 269 ),
			array ( 'id' => 49 , 'code' => 'CG' , 'name' => " Congo ", 'phonecode' => 242 ),
			array ( 'id' => 50 , 'code' => 'CD' , 'name' => " Congo La République Démocratique Du ", 'phonecode' => 242 ),
			array ( 'id' => 51 , 'code' => 'CK' , 'name' => " Îles Cook ", 'phonecode' => 682 ),
			array ( 'id' => 52 , 'code' => 'CR' , 'name' => " Costa Rica ", 'phonecode' => 506 ),
			array ( 'id' => 53 , 'code' => 'CI' , 'name' => " Cote D Ivoire (Côte d'Ivoire) ", 'phonecode' => 225 ),
			array ( 'id' => 54 , 'code' => 'HR' , 'name' => " Croatie (Hrvatska) ", 'phonecode' => 385 ),
			array ( 'id' => 55 , 'code' => 'CU' , 'name' => " Cuba ", 'phonecode' => 53 ),
			array ( 'id' => 56 , 'code' => 'CY' , 'name' => " Chypre ", 'phonecode' => 357 ),
			array ( 'id' => 57 , 'code' => 'CZ' , 'name' => " République tchèque ", 'phonecode' => 420 ),
			array ( 'id' => 58 , 'code' => 'DK' , 'name' => " Danemark ", 'phonecode' => 45 ),
			array ( 'id' => 59 , 'code' => 'DJ' , 'name' => " Djibouti ", 'phonecode' => 253 ),
			array ( 'id' => 60 , 'code' => 'DM' , 'name' => " Dominique ", 'phonecode' => 1767 ),
			array ( 'id' => 61 , 'code' => 'DO' , 'name' => " République dominicaine ", 'phonecode' => 1809 ),
			array ( 'id' => 62 , 'code' => 'TP' , 'name' => " Timor oriental ", 'phonecode' => 670 ),
			array ( 'id' => 63 , 'code' => 'EC' , 'name' => " Equateur ", 'phonecode' => 593 ),
			array ( 'id' => 64 , 'code' => 'EG' , 'name' => " Egypte ", 'phonecode' => 20 ),
			array ( 'id' => 65 , 'code' => 'SV' , 'name' => " Salvador ", 'phonecode' => 503 ),
			array ( 'id' => 66 , 'code' => 'GQ' , 'name' => " Guinée équatoriale ", 'phonecode' => 240 ),
			array ( 'id' => 67 , 'code' => 'ER' , 'name' => " Erythrée ", 'phonecode' => 291 ),
			array ( 'id' => 68 , 'code' => 'EE' , 'name' => " Estonie ", 'phonecode' => 372 ),
			array ( 'id' => 69 , 'code' => 'ET' , 'name' => " Éthiopie ", 'phonecode' => 251 ),
			array ( 'id' => 70 , 'code' => 'XA' , 'name' => " Territoires extérieurs de l'Australie ", 'phonecode' => 61 ),
			array ( 'id' => 71 , 'code' => 'FK' , 'name' => " Falkland Islands ", 'phonecode' => 500 ),
			array ( 'id' => 72 , 'code' => 'FO' , 'name' => " Îles Féroé ", 'phonecode' => 298 ),
			array ( 'id' => 73 , 'code' => 'FJ' , 'name' => " Îles Fidji ", 'phonecode' => 679 ),
			array ( 'id' => 74 , 'code' => 'FI' , 'name' => " Finlande ", 'phonecode' => 358 ),
			array ( 'id' => 75 , 'code' => 'FR' , 'name' => " France ", 'phonecode' => 33 ),
			array ( 'id' => 76 , 'code' => 'GF' , 'name' => " Guyane française ", 'phonecode' => 594 ),
			array ( 'id' => 77 , 'code' => 'PF' , 'name' => " Polynésie française ", 'phonecode' => 689 ),
			array ( 'id' => 78 , 'code' => 'TF' , 'name' => " Terres Australes Françaises ", 'phonecode' => 0 ),
			array ( 'id' => 79 , 'code' => 'GA' , 'name' => " Gabon ", 'phonecode' => 241 ),
			array ( 'id' => 80 , 'code' => 'GM' , 'name' => " Gambia The ", 'phonecode' => 220 ),
			array ( 'id' => 81 , 'code' => 'GE' , 'name' => " Géorgie ", 'phonecode' => 995 ),
			array ( 'id' => 82 , 'code' => 'DE' , 'name' => " Germany ", 'phonecode' => 49 ),
			array ( 'id' => 83 , 'code' => 'GH' , 'name' => " Ghana ", 'phonecode' => 233 ),
			array ( 'id' => 84 , 'code' => 'GI' , 'name' => " Gibraltar ", 'phonecode' => 350 ),
			array ( 'id' => 85 , 'code' => 'GR' , 'name' => " Grèce ", 'phonecode' => 30 ),
			array ( 'id' => 86 , 'code' => 'GL' , 'name' => " Groenland ", 'phonecode' => 299 ),
			array ( 'id' => 87 , 'code' => 'GD' , 'name' => " Grenade ", 'phonecode' => 1473 ),
			array ( 'id' => 88 , 'code' => 'GP' , 'name' => " Guadeloupe ", 'phonecode' => 590 ),
			array ( 'id' => 89 , 'code' => 'GU' , 'name' => " Guam ", 'phonecode' => 1671 ),
			array ( 'id' => 90 , 'code' => 'GT' , 'name' => " Guatemala ", 'phonecode' => 502 ),
			array ( 'id' => 91 , 'code' => 'XU' , 'name' => " Guernesey et Aurigny ", 'phonecode' => 44 ),
			array ( 'id' => 92 , 'code' => 'GN' , 'name' => " Guinée ", 'phonecode' => 224 ),
			array ( 'id' => 93 , 'code' => 'GW' , 'name' => " Guinée-Bissau ", 'phonecode' => 245 ),
			array ( 'id' => 94 , 'code' => 'GY' , 'name' => " Guyane ", 'phonecode' => 592 ),
			array ( 'id' => 95 , 'code' => 'HT' , 'name' => " Haïti ", 'phonecode' => 509 ),
			array ( 'id' => 96 , 'code' => 'HM' , 'name' => " Îles Heard et McDonald ", 'phonecode' => 0 ),
			array ( 'id' => 97 , 'code' => 'HN' , 'name' => " Honduras ", 'phonecode' => 504 ),
			array ( 'id' => 98 , 'code' => 'HK' , 'name' => " Hong Kong SAR ", 'phonecode' => 852 ),
			array ( 'id' => 99 , 'code' => 'HU' , 'name' => " Hongrie ", 'phonecode' => 36 ),
			array ( 'id' => 100 , 'code' => 'IS' , 'name' => " Islande ", 'phonecode' => 354 ),
			array ( 'id' => 101 , 'code' => 'IN' , 'name' => " Inde ", 'phonecode' => 91 ),
			array ( 'id' => 102 , 'code' => 'ID' , 'name' => " Indonésie ", 'phonecode' => 62 ),
			array ( 'id' => 103 , 'code' => 'IR' , 'name' => " Iran ", 'phonecode' => 98 ),
			array ( 'id' => 104 , 'code' => 'IQ' , 'name' => " Irak ", 'phonecode' => 964 ),
			array ( 'id' => 105 , 'code' => 'IE' , 'name' => " Irlande ", 'phonecode' => 353 ),
			array ( 'id' => 106 , 'code' => 'IL' , 'name' => " Israël ", 'phonecode' => 972 ),
			array ( 'id' => 107 , 'code' => 'IT' , 'name' => " Italie ", 'phonecode' => 39 ),
			array ( 'id' => 108 , 'code' => 'JM' , 'name' => " Jamaïque ", 'phonecode' => 1876 ),
			array ( 'id' => 109 , 'code' => 'JP' , 'name' => " Japon ", 'phonecode' => 81 ),
			array ( 'id' => 110 , 'code' => 'XJ' , 'name' => " Jersey ", 'phonecode' => 44 ),
			array ( 'id' => 111 , 'code' => 'JO' , 'name' => " Jordan ", 'phonecode' => 962 ),
			array ( 'id' => 112 , 'code' => 'KZ' , 'name' => " Kazakhstan ", 'phonecode' => 7 ),
			array ( 'id' => 113 , 'code' => 'KE' , 'name' => " Kenya ", 'phonecode' => 254 ),
			array ( 'id' => 114 , 'code' => 'KI' , 'name' => " Kiribati ", 'phonecode' => 686 ),
			array ( 'id' => 115 , 'code' => 'KP' , 'name' => " Corée du Nord ", 'phonecode' => 850 ),
			array ( 'id' => 116 , 'code' => 'KR' , 'name' => " Corée du Sud ", 'phonecode' => 82 ),
			array ( 'id' => 117 , 'code' => 'KW' , 'name' => " Koweït ", 'phonecode' => 965 ),
			array ( 'id' => 118 , 'code' => 'KG' , 'name' => " Kirghizistan ", 'phonecode' => 996 ),
			array ( 'id' => 119 , 'code' => 'LA' , 'name' => " Laos ", 'phonecode' => 856 ),
			array ( 'id' => 120 , 'code' => 'LV' , 'name' => " Lettonie ", 'phonecode' => 371 ),
			array ( 'id' => 121 , 'code' => 'LB' , 'name' => " Liban ", 'phonecode' => 961 ),
			array ( 'id' => 122 , 'code' => 'LS' , 'name' => " Lesotho ", 'phonecode' => 266 ),
			array ( 'id' => 123 , 'code' => 'LR' , 'name' => " Libéria ", 'phonecode' => 231 ),
			array ( 'id' => 124 , 'code' => 'LY' , 'name' => " Libye ", 'phonecode' => 218 ),
			array ( 'id' => 125 , 'code' => 'LI' , 'name' => " Liechtenstein ", 'phonecode' => 423 ),
			array ( 'id' => 126 , 'code' => 'LT' , 'name' => " Lituanie ", 'phonecode' => 370 ),
			array ( 'id' => 127 , 'code' => 'LU' , 'name' => " Luxembourg ", 'phonecode' => 352 ),
			array ( 'id' => 128 , 'code' => 'MO' , 'name' => " Macau SAR ", 'phonecode' => 853 ),
			array ( 'id' => 129 , 'code' => 'MK' , 'name' => " Macédoine ", 'phonecode' => 389 ),
			array ( 'id' => 130 , 'code' => 'MG' , 'name' => " Madagascar ", 'phonecode' => 261 ),
			array ( 'id' => 131 , 'code' => 'MW' , 'name' => " Mali ", 'phonecode' => 265 ),
			array ( 'id' => 132 , 'code' => 'MY' , 'name' => " Malaysia ", 'phonecode' => 60 ),
			array ( 'id' => 133 , 'code' => 'MV' , 'name' => " Maldives ", 'phonecode' => 960 ),
			array ( 'id' => 134 , 'code' => 'ML' , 'name' => " Mali ", 'phonecode' => 223 ),
			array ( 'id' => 135 , 'code' => 'MT' , 'name' => " Malte ", 'phonecode' => 356 ),
			array ( 'id' => 136 , 'code' => 'XM' , 'name' => " Man (Île de) ", 'phonecode' => 44 ),
			array ( 'id' => 137 , 'code' => 'MH' , 'name' => " Îles Marshall ", 'phonecode' => 692 ),
			array ( 'id' => 138 , 'code' => 'MQ' , 'name' => " Martinique ", 'phonecode' => 596 ),
			array ( 'id' => 139 , 'code' => 'MR' , 'name' => " Mauritanie ", 'phonecode' => 222 ),
			array ( 'id' => 140 , 'code' => 'MU' , 'name' => " Maurice ", 'phonecode' => 230 ),
			array ( 'id' => 141 , 'code' => 'YT' , 'name' => " Mayotte ", 'phonecode' => 269 ),
			array ( 'id' => 142 , 'code' => 'MX' , 'name' => " Mexique ", 'phonecode' => 52 ),
			array ( 'id' => 143 , 'code' => 'FM' , 'name' => " Micronésie ", 'phonecode' => 691 ),
			array ( 'id' => 144 , 'code' => 'MD' , 'name' => " Moldavie ", 'phonecode' => 373 ),
			array ( 'id' => 145 , 'code' => 'MC' , 'name' => " Monaco ", 'phonecode' => 377 ),
			array ( 'id' => 146 , 'code' => 'MN' , 'name' => " Mongolie ", 'phonecode' => 976 ),
			array ( 'id' => 147 , 'code' => 'MS' , 'name' => " Montserrat ", 'phonecode' => 1664 ),
			array ( 'id' => 148 , 'code' => 'MA' , 'name' => " Maroc ", 'phonecode' => 212 ),
			array ( 'id' => 149 , 'code' => 'MZ' , 'name' => " Mozambique ", 'phonecode' => 258 ),
			array ( 'id' => 150 , 'code' => 'MM' , 'name' => " Birmanie ", 'phonecode' => 95 ),
			array ( 'id' => 151 , 'code' => 'NA' , 'name' => " Namibie ", 'phonecode' => 264 ),
			array ( 'id' => 152 , 'code' => 'NR' , 'name' => " Nauru ", 'phonecode' => 674 ),
			array ( 'id' => 153 , 'code' => 'NP' , 'name' => " Népal ", 'phonecode' => 977 ),
			array ( 'id' => 154 , 'code' => 'AN' , 'name' => " Antilles Néerlandaises ", 'phonecode' => 599 ),
			array ( 'id' => 155 , 'code' => 'NL' , 'name' => " Pays-Bas Le ", 'phonecode' => 31 ),
			array ( 'id' => 156 , 'code' => 'NC' , 'name' => " Nouvelle Calédonie ", 'phonecode' => 687 ),
			array ( 'id' => 157 , 'code' => 'NZ' , 'name' => " Nouvelle-Zélande ", 'phonecode' => 64 ),
			array ( 'id' => 158 , 'code' => 'NI' , 'name' => " Nicaragua ", 'phonecode' => 505 ),
			array ( 'id' => 159 , 'code' => 'NE' , 'name' => " Niger ", 'phonecode' => 227 ),
			array ( 'id' => 160 , 'code' => 'NG' , 'name' => " Nigéria ", 'phonecode' => 234 ),
			array ( 'id' => 161 , 'code' => 'NU' , 'name' => " Niger ", 'phonecode' => 683 ),
			array ( 'id' => 162 , 'code' => 'NF' , 'name' => " Norfolk Island ", 'phonecode' => 672 ),
			array ( 'id' => 163 , 'code' => 'MP' , 'name' => " Îles Mariannes du Nord ", 'phonecode' => 1670 ),
			array ( 'id' => 164 , 'code' => 'NO' , 'name' => " Norway ", 'phonecode' => 47 ),
			array ( 'id' => 165 , 'code' => 'OM' , 'name' => " Oman ", 'phonecode' => 968 ),
			array ( 'id' => 166 , 'code' => 'PK' , 'name' => " Pakistan ", 'phonecode' => 92 ),
			array ( 'id' => 167 , 'code' => 'PW' , 'name' => " Palaos ", 'phonecode' => 680 ),
			array ( 'id' => 168 , 'code' => 'PS' , 'name' => " Territoire palestinien occupé ", 'phonecode' => 970 ),
			array ( 'id' => 169 , 'code' => 'PA' , 'name' => " Panama ", 'phonecode' => 507 ),
			array ( 'id' => 170 , 'code' => 'PG' , 'name' => " Papouasie-Nouvelle-Guinée ", 'phonecode' => 675 ),
			array ( 'id' => 171 , 'code' => 'PY' , 'name' => " Paraguay ", 'phonecode' => 595 ),
			array ( 'id' => 172 , 'code' => 'PE' , 'name' => " Pérou ", 'phonecode' => 51 ),
			array ( 'id' => 173 , 'code' => 'PH' , 'name' => " Philippines ", 'phonecode' => 63 ),
			array ( 'id' => 174 , 'code' => 'PN' , 'name' => " Pitcairn Island ", 'phonecode' => 0 ),
			array ( 'id' => 175 , 'code' => 'PL' , 'name' => " Pologne ", 'phonecode' => 48 ),
			array ( 'id' => 176 , 'code' => 'PT' , 'name' => " Portugal ", 'phonecode' => 351 ),
			array ( 'id' => 177 , 'code' => 'PR' , 'name' => " Porto Rico ", 'phonecode' => 1787 ),
			array ( 'id' => 178 , 'code' => 'QA' , 'name' => " Qatar ", 'phonecode' => 974 ),
			array ( 'id' => 179 , 'code' => 'RE' , 'name' => " Réunion ", 'phonecode' => 262 ),
			array ( 'id' => 180 , 'code' => 'RO' , 'name' => " Roumanie ", 'phonecode' => 40 ),
			array ( 'id' => 181 , 'code' => 'RU' , 'name' => " Russie ", 'phonecode' => 70 ),
			array ( 'id' => 182 , 'code' => 'RW' , 'name' => " Rwanda ", 'phonecode' => 250 ),
			array ( 'id' => 183 , 'code' => 'SH' , 'name' => " Sainte-Hélène ", 'phonecode' => 290 ),
			array ( 'id' => 184 , 'code' => 'KN' , 'name' => " Saint-Kitts-et-Nevis ", 'phonecode' => 1869 ),
			array ( 'id' => 185 , 'code' => 'LC' , 'name' => " Sainte-Lucie ", 'phonecode' => 1758 ),
			array ( 'id' => 186 , 'code' => 'PM' , 'name' => " Saint Pierre et Miquelon ", 'phonecode' => 508 ),
			array ( 'id' => 187 , 'code' => 'VC' , 'name' => " Saint Vincent Et Les Grenadines ", 'phonecode' => 1784 ),
			array ( 'id' => 188 , 'code' => 'WS' , 'name' => " Samoa ", 'phonecode' => 684 ),
			array ( 'id' => 189 , 'code' => 'SM' , 'name' => " Saint-Marin ", 'phonecode' => 378 ),
			array ( 'id' => 190 , 'code' => 'ST' , 'name' => " Sao Tomé et Principe ", 'phonecode' => 239 ),
			array ( 'id' => 191 , 'code' => 'SA' , 'name' => " Arabie Saoudite ", 'phonecode' => 966 ),
			array ( 'id' => 192 , 'code' => 'SN' , 'name' => " Sénégal ", 'phonecode' => 221 ),
			array ( 'id' => 193 , 'code' => 'RS' , 'name' => " Serbie ", 'phonecode' => 381 ),
			array ( 'id' => 194 , 'code' => 'SC' , 'name' => " Seychelles ", 'phonecode' => 248 ),
			array ( 'id' => 195 , 'code' => 'SL' , 'name' => " Sierra Leone ", 'phonecode' => 232 ),
			array ( 'id' => 196 , 'code' => 'SG' , 'name' => " Singapour ", 'phonecode' => 65 ),
			array ( 'id' => 197 , 'code' => 'SK' , 'name' => " Slovaquie ", 'phonecode' => 421 ),
			array ( 'id' => 198 , 'code' => 'SI' , 'name' => " Slovénie ", 'phonecode' => 386 ),
			array ( 'id' => 199 , 'code' => 'XG' , 'name' => " Petits territoires du Royaume-Uni ", 'phonecode' => 44 ),
			array ( 'id' => 200 , 'code' => 'SB' , 'name' => " Îles Salomon ", 'phonecode' => 677 ),
			array ( 'id' => 201 , 'code' => 'SO' , 'name' => " Somalie ", 'phonecode' => 252 ),
			array ( 'id' => 202 , 'code' => 'ZA' , 'name' => " Afrique du Sud ", 'phonecode' => 27 ),
			array ( 'id' => 203 , 'code' => 'GS' , 'name' => " Géorgie du Sud ", 'phonecode' => 0 ),
			array ( 'id' => 204 , 'code' => 'SS' , 'name' => " Soudan du Sud ", 'phonecode' => 211 ),
			array ( 'id' => 205 , 'code' => 'ES' , 'name' => " Espagne ", 'phonecode' => 34 ),
			array ( 'id' => 206 , 'code' => 'LK' , 'name' => " Sri Lanka ", 'phonecode' => 94 ),
			array ( 'id' => 207 , 'code' => 'SD' , 'name' => " Soudan ", 'phonecode' => 249 ),
			array ( 'id' => 208 , 'code' => 'SR' , 'name' => " Suriname ", 'phonecode' => 597 ),
			array ( 'id' => 209 , 'code' => 'SJ' , 'name' => " Îles Svalbard et Jan Mayen ", 'phonecode' => 47 ),
			array ( 'id' => 210 , 'code' => 'SZ' , 'name' => " Swaziland ", 'phonecode' => 268 ),
			array ( 'id' => 211 , 'code' => 'SE' , 'name' => " Suède ", 'phonecode' => 46 ),
			array ( 'id' => 212 , 'code' => 'CH' , 'name' => " Suisse ", 'phonecode' => 41 ),
			array ( 'id' => 213 , 'code' => 'SY' , 'name' => " Syrie ", 'phonecode' => 963 ),
			array ( 'id' => 214 , 'code' => 'TW' , 'name' => " Taïwan ", 'phonecode' => 886 ),
			array ( 'id' => 215 , 'code' => 'TJ' , 'name' => " Tadjikistan ", 'phonecode' => 992 ),
			array ( 'id' => 216 , 'code' => 'TZ' , 'name' => " Tanzanie ", 'phonecode' => 255 ),
			array ( 'id' => 217 , 'code' => 'TH' , 'name' => " Thaïlande ", 'phonecode' => 66 ),
			array ( 'id' => 218 , 'code' => 'TG' , 'name' => " Togo ", 'phonecode' => 228 ),
			array ( 'id' => 219 , 'code' => 'TK' , 'name' => " Tokelau ", 'phonecode' => 690 ),
			array ( 'id' => 220 , 'code' => 'TO' , 'name' => " Tonga ", 'phonecode' => 676 ),
			array ( 'id' => 221 , 'code' => 'TT' , 'name' => " Trinité-et-Tobago ", 'phonecode' => 1868 ),
			array ( 'id' => 222 , 'code' => 'TN' , 'name' => " Tunisie ", 'phonecode' => 216 ),
			array ( 'id' => 223 , 'code' => 'TR' , 'name' => " Turquie ", 'phonecode' => 90 ),
			array ( 'id' => 224 , 'code' => 'TM' , 'name' => " Turkménistan ", 'phonecode' => 7370 ),
			array ( 'id' => 225 , 'code' => 'TC' , 'name' => " Îles Turques et Caïques ", 'phonecode' => 1649 ),
			array ( 'id' => 226 , 'code' => 'TV' , 'name' => " Tuvalu ", 'phonecode' => 688 ),
			array ( 'id' => 227 , 'code' => 'UG' , 'name' => " Ouganda ", 'phonecode' => 256 ),
			array ( 'id' => 228 , 'code' => 'UA' , 'name' => " Ukraine ", 'phonecode' => 380 ),
			array ( 'id' => 229 , 'code' => 'AE' , 'name' => " Emirats Arabes Unis ", 'phonecode' => 971 ),
			array ( 'id' => 230 , 'code' => 'GB' , 'name' => " Royaume-Uni ", 'phonecode' => 44 ),
			array ( 'id' => 231 , 'code' => 'US' , 'name' => " United States ", 'phonecode' => 1 ),
			array ( 'id' => 232 , 'code' => 'UM' , 'name' => " Îles mineures éloignées des États-Unis ", 'phonecode' => 1 ),
			array ( 'id' => 233 , 'code' => 'UY' , 'name' => " Uruguay ", 'phonecode' => 598 ),
			array ( 'id' => 234 , 'code' => 'UZ' , 'name' => " Ouzbékistan ", 'phonecode' => 998 ),
			array ( 'id' => 235 , 'code' => 'VU' , 'name' => " Vanuatu ", 'phonecode' => 678 ),
			array ( 'id' => 236 , 'code' => 'VA' , 'name' => " État de la Cité du Vatican (Saint-Siège) ", 'phonecode' => 39 ),
			array ( 'id' => 237 , 'code' => 'VE' , 'name' => " Venezuela ", 'phonecode' => 58 ),
			array ( 'id' => 238 , 'code' => 'VN' , 'name' => " Vietnam ", 'phonecode' => 84 ),
			array ( 'id' => 239 , 'code' => 'VG' , 'name' => " Îles Vierges (Britanniques) ", 'phonecode' => 1284 ),
			array ( 'id' => 240 , 'code' => 'VI' , 'name' => " Îles Vierges (US) ", 'phonecode' => 1340 ),
			array ( 'id' => 241 , 'code' => 'WF' , 'name' => " Îles Wallis et Futuna ", 'phonecode' => 681 ),
			array ( 'id' => 242 , 'code' => 'EH' , 'name' => " Sahara occidental ", 'phonecode' => 212 ),
			array ( 'id' => 243 , 'code' => 'YE' , 'name' => " Yémen ", 'phonecode' => 967 ),
			array ( 'id' => 244 , 'code' => 'YU' , 'name' => " Yougoslavie ", 'phonecode' => 38 ),
			array ( 'id' => 245 , 'code' => 'ZM' , 'name' => " Zambie ", 'phonecode' => 260 ),
			array ( 'id' => 246 , 'code' => 'ZW' , 'name' => " Zimbabwe ", 'phonecode' => 263 ),
			);
		DB::table('pays')->insert($pays);
    }
}
